### ISSUE TITLE
Why is highWaterMark set to 0 for `fromAnyIterable`

### ISSUE THREAD

**Issue by wong2** [Sec-ant/readable-stream#32]
What is the reason behind this decision?

**Comment by Sec-ant** [comment]
Actually, I forgot, probably trying to pass some of the test cases. Welcome to contribute if this is misimplemented.

**Comment by wong2** [comment]
I found that this is actually consistent with Node.js's ReadableStream.from implementation, so it should be fine: https://github.com/nodejs/node/blob/cad73dadba005ddb5b1d810e0bfbcd7034b94e35/lib/internal/webstreams/readablestream.js#L1352
